function v4Vi(i){
 var b=[];
 if(i===0)b=[V4C('Khi gặp dấu chấm, em nên:',['Dừng nghỉ rõ hơn','Đọc liền không nghỉ','Đọc thật nhanh'],0,'📖'),V4C('Câu “Bạn Lan học rất chăm.” nên đọc với giọng:',['Tự nhiên, rõ ràng','La thật to','Ngắt sau mỗi từ'],0,'🎙️'),V4M('Chọn những dấu thường cần ngắt nghỉ khi đọc.',['.','?','!',','],[0,1,2,3],'⏸️'),V4C('Từ nào có 2 tiếng?',['học sinh','bàn','đẹp'],0,'🔤'),V4O('Sắp xếp để tạo câu đọc tự nhiên.',['Em','yêu','trường em'],['Em','yêu','trường em'],'🧩')];
 else if(i===1)b=[V4C('Minh đi đâu vào sáng chủ nhật?',['Đến trường','Ra công viên','Về quê'],1,'🐰',{passage:V4PASS}),V4C('Minh và bố đã làm gì?',['Tưới cây và nhặt lá','Đá bóng','Mua đồ chơi'],0,'🌳',{passage:V4PASS}),V4C('Vì sao Minh vui?',['Được nghỉ học','Công viên sạch đẹp hơn','Được ăn kem'],1,'😊',{passage:V4PASS}),V4M('Những việc nào giúp công viên sạch đẹp?',['Tưới cây','Nhặt lá','Vứt rác','Bẻ cành'],[0,1],'✅',{passage:V4PASS}),V4C('Ý chính của đoạn là:',['Minh cùng bố chăm sóc công viên','Minh đi học','Minh mua cây'],0,'📚',{passage:V4PASS})];
 else if(i===2)b=[V4I('Bấm 🔊 rồi viết từ em nghe được.',['chăm chỉ'],'🎧',{speak:'chăm chỉ'}),V4I('Bấm 🔊 rồi viết từ em nghe được.',['ngôi trường'],'🎧',{speak:'ngôi trường'}),V4C('Từ nào viết đúng?',['sạch sẽ','xạch sẽ','sạch sẻ'],0,'✍️'),V4C('Câu nào viết hoa đúng?',['em tên là Lan.','Em tên là Lan.','Em Tên là lan.'],1,'📝'),V4I('Bấm 🔊 rồi viết từ em nghe được.',['gia đình'],'🎧',{speak:'gia đình'})];
 else if(i===3)b=[V4C('Điền c/k: “...on cá”',['c','k'],0,'🐟'),V4C('Điền g/gh: “...ế gỗ”',['g','gh'],1,'🪑'),V4C('Điền ng/ngh: “...ỉ hè”',['ng','ngh'],1,'🏖️'),V4C('Từ nào viết đúng?',['con nghé','con ngé','con ghé'],0,'🐃'),V4M('Chọn các từ viết đúng.',['kể chuyện','cể chuyện','ghế đá','gế đá'],[0,2],'🔤')];
 else if(i===4)b=[V4C('Từ nào chỉ sự vật?',['cái bàn','chạy','đẹp'],0,'🪑'),V4M('Chọn các từ chỉ sự vật.',['cô giáo','con mèo','đọc','cây bàng'],[0,1,3],'🌳'),V4C('“Bầu trời” là từ chỉ:',['sự vật','hoạt động','đặc điểm'],0,'☁️'),V4C('Từ nào chỉ người?',['bác sĩ','cặp sách','xanh'],0,'👩‍⚕️'),V4O('Xếp các từ thành nhóm từ chỉ sự vật.',['học sinh','quyển vở','cây phượng'],['học sinh','quyển vở','cây phượng'],'📚')];
 else if(i===5)b=[V4C('Từ nào chỉ hoạt động?',['chạy','đỏ','cái bàn'],0,'🏃'),V4M('Chọn các từ chỉ hoạt động.',['đọc','viết','xanh','nhảy'],[0,1,3],'🤸'),V4C('Trong câu “Mẹ nấu cơm”, từ chỉ hoạt động là:',['Mẹ','nấu','cơm'],1,'🍲'),V4C('Từ nào không chỉ hoạt động?',['hát','ngủ','cao'],2,'🎵'),V4I('Điền từ chỉ hoạt động: “Bé ___ sách.”',['đọc'],'📖')];
 else if(i===6)b=[V4C('Từ nào chỉ đặc điểm?',['xanh','chạy','cái cây'],0,'🌈'),V4M('Chọn các từ chỉ đặc điểm.',['cao','ngoan','học','đỏ'],[0,1,3],'🎨'),V4C('Trong câu “Bông hoa rất đẹp”, từ chỉ đặc điểm là:',['hoa','rất','đẹp'],2,'🌸'),V4C('Từ trái nghĩa với “cao” là:',['thấp','dài','đẹp'],0,'↕️'),V4I('Điền một từ phù hợp: “Bầu trời rất ___.”',['xanh','trong xanh','cao'],'☀️')];
 else if(i===7)b=[V4C('Câu nào thuộc kiểu “Ai làm gì?”',['Lan đang đọc sách.','Lan là học sinh.','Lan rất chăm.'],0,'💬'),V4C('Câu “Bố em là bác sĩ.” thuộc kiểu:',['Ai làm gì?','Ai là gì?','Ai thế nào?'],1,'👨‍⚕️'),V4C('Câu “Chú mèo rất nhanh nhẹn.” thuộc kiểu:',['Ai thế nào?','Ai làm gì?','Ai là gì?'],0,'🐱'),V4O('Sắp xếp thành câu đúng.',['Bạn Nam','đang đá','bóng.'],['Bạn Nam','đang đá','bóng.'],'🧩'),V4I('Điền từ còn thiếu: “Mẹ em ___ giáo viên.”',['là'],'✍️')];
 else if(i===8)b=[V4C('Chọn dấu phù hợp: “Bạn tên là gì…”',['.','?','!'],1,'❓'),V4C('Chọn dấu phù hợp: “Ôi, bông hoa đẹp quá…”',['.','?','!'],2,'🌸'),V4C('Cuối câu kể thường dùng:',['Dấu chấm','Dấu hỏi','Dấu hai chấm'],0,'📝'),V4M('Chọn các dấu kết thúc câu.',['.','?','!',','],[0,1,2],'✅'),V4C('Trong câu liệt kê “Em có bút, vở, thước.” dấu phẩy dùng để:',['Ngăn cách các từ cùng loại','Kết thúc câu hỏi','Thể hiện cảm xúc'],0,'📚')];
 else if(i===9)b=[V4C('Từ nào thuộc chủ điểm trường học?',['bảng','nồi cơm','cá heo'],0,'🏫'),V4M('Chọn từ thuộc chủ điểm gia đình.',['ông bà','bố mẹ','thầy giáo','anh chị'],[0,1,3],'👨‍👩‍👧‍👦'),V4C('Từ nào thuộc chủ điểm thiên nhiên?',['dòng sông','bút chì','cặp sách'],0,'🏞️'),V4C('Từ nào gần nghĩa với “chăm chỉ”?',['siêng năng','lười biếng','ồn ào'],0,'📘'),V4I('Điền từ: “Mùa hè, cây phượng nở hoa màu ___.”',['đỏ'],'🌺')];
 else if(i===10)b=[V4O('Sắp xếp thành câu hoàn chỉnh.',['Buổi sáng,','em','đi học đúng giờ.'],['Buổi sáng,','em','đi học đúng giờ.'],'📝'),V4C('Câu mở đầu phù hợp khi kể về trường em là:',['Trường em rất đẹp.','Hôm qua em ăn cơm.','Con mèo đang ngủ.'],0,'🏫'),V4M('Một đoạn văn ngắn nên có:',['Các câu cùng nói về một chủ đề','Ý sắp xếp hợp lí','Câu không liên quan'],[0,1],'📚'),V4I('Điền từ để câu đủ ý: “Em rất ___ cô giáo của em.”',['yêu','quý','yêu quý'],'❤️'),V4C('Câu kết phù hợp khi kể về người thân:',['Em rất yêu mẹ.','Bầu trời có mây.','Em có cây bút.'],0,'👩')];
 else if(i===11)b=[V4O('Sắp xếp diễn biến hợp lí.',['Thỏ và rùa thi chạy.','Thỏ chủ quan nằm ngủ.','Rùa kiên trì về đích trước.'],['Thỏ và rùa thi chạy.','Thỏ chủ quan nằm ngủ.','Rùa kiên trì về đích trước.'],'🐢'),V4C('Khi kể chuyện, em nên:',['Kể theo trình tự','Kể lộn xộn','Chỉ nói một từ'],0,'📚'),V4C('Nhân vật kiên trì trong truyện Thỏ và Rùa là:',['Thỏ','Rùa','Cả hai như nhau'],1,'🐢'),V4M('Khi kể theo tranh, em cần chú ý:',['Nhân vật','Sự việc','Trình tự tranh','Màu áo của mình'],[0,1,2],'🖼️'),V4I('Điền từ phù hợp: “Rùa tuy chậm nhưng rất ___.”',['kiên trì','cố gắng'],'🌟')];
 else if(i===12)b=[V4C('Khi bạn đang nói, em nên:',['Lắng nghe','Ngắt lời liên tục','Bỏ đi'],0,'🎧'),V4C('Khi muốn hỏi lại, cách nói lịch sự là:',['Bạn có thể nói lại giúp mình không?','Nói lại đi!','Mình không nghe!'],0,'💬'),V4M('Khi trình bày trước lớp, em nên:',['Nói rõ ràng','Nhìn người nghe','Nói quá nhỏ','Giữ thái độ tự tin'],[0,1,3],'🎤'),V4I('Bấm 🔊, nghe và viết từ cuối câu.',['trường'],'🎧',{speak:'Em rất yêu mái trường'}),V4C('Sau khi bạn trình bày, em có thể:',['Nêu nhận xét lịch sự','Cười chê','Bỏ ra ngoài'],0,'🤝')];
 else b=[V4C('Từ nào chỉ hoạt động?',['học','xanh','bàn'],0,'🏆'),V4C('“Bạn khỏe không…” cần dấu:',['.','?','!'],1,'❓'),V4M('Chọn từ viết đúng.',['nghỉ hè','ghế đá','gế đá','ngỉ hè'],[0,1],'✅'),V4O('Sắp xếp thành câu.',['Chúng em','chăm sóc','cây xanh.'],['Chúng em','chăm sóc','cây xanh.'],'🧩'),V4I('Điền từ: “Bông hoa rất ___.”',['đẹp','xinh','xinh đẹp'],'🌸')];
 return b;
}
function rows(type,list,done,practice){
 return '<div class="curriculum-note">📘 <b>Lộ trình chuẩn app:</b> kỹ năng nền tảng → luyện tập → vận dụng; game chỉ mở theo kiến thức đã học.</div><div class="lesson-list">'+list.map(function(x,i){var locked=i>done,best=state.best[type+'-'+i]||0,stars=best?'⭐'.repeat(Math.min(3,best))+'☆'.repeat(Math.max(0,3-best)):(i<done?'⭐⭐⭐':'⭐☆☆');return '<button class="lesson-row '+(locked?'locked':'')+'" data-lesson="'+i+'" data-type="'+type+'" '+(locked?'data-locked="1"':'')+'><span class="lesson-index c'+((i%5)+1)+'">'+(i+1)+'</span><span class="lesson-emoji">'+(practice?'🎯':x[2])+'</span><span class="lesson-copy"><strong>'+(practice?'Luyện tập: ':'')+x[0]+'</strong><small>'+(practice?'Phiên 5 câu • nhiều dạng tương tác':x[1])+'</small></span><span class="lesson-state">'+(locked?'🔒':stars)+' ›</span></button>'}).join('')+'</div>';
}
function gameCards(type,done){return '<div class="curriculum-note">🎮 Mini game bám đúng kỹ năng của bài và chỉ mở sau khi bé đã học đủ nội dung liên quan.</div><div class="game-grid">'+V4GAMES[type].map(function(g){return '<button class="game-tile '+(done<g[2]?'locked':'')+'" data-game="'+type+'" data-variant="'+g[3]+'" '+(done<g[2]?'data-locked="1"':'')+'><span class="game-art">'+g[1]+'</span><strong>'+g[0]+'</strong><small>5 vòng • đúng kiến thức lớp 2</small><em>'+(done<g[2]?'🔒 Mở sau bài '+g[2]:'Chơi ngay ›')+'</em></button>'}).join('')+'</div>'}
function dynamic(){
 $$('[data-lesson]').forEach(function(b){b.onclick=function(){if(b.dataset.locked)return toast('🔒 Hãy hoàn thành bài trước để mở bài này nhé!');exercise(b.dataset.type,+b.dataset.lesson)}});
 $$('[data-game]').forEach(function(b){b.onclick=function(){if(b.dataset.locked)return toast('🔒 Học đủ kỹ năng để mở game này nhé!');game(b.dataset.game,b.dataset.variant)}});
}
