var V4GEN={
 'math-balloon':function(){var a=5+Math.floor(Math.random()*25),b=2+Math.floor(Math.random()*15),ok=a+b;return {title:'Bắn bóng số',q:a+' + '+b+' = ?',answer:String(ok),choices:v4Shuffle([ok,ok+2,ok-2,ok+5].map(String)),decor:'🎈'}},
 'math-race':function(){var a=20+Math.floor(Math.random()*50),b=2+Math.floor(Math.random()*20),ok=a-b;return {title:'Đua xe phép tính',q:a+' - '+b+' = ?',answer:String(ok),choices:v4Shuffle([ok,ok+10,ok-10,ok+2].map(String)),decor:'🏎️'}},
 'shape':function(){var s=[['Hình có 3 cạnh?','Tam giác',['Tam giác','Hình tròn','Hình vuông','Khối cầu']],['Vật giống khối cầu?','Quả bóng',['Hộp sữa','Quả bóng','Quyển sách','Cái bảng']]],x=s[Math.floor(Math.random()*s.length)];return {title:'Xếp hình toán học',q:x[0],answer:x[1],choices:v4Shuffle(x[2]),decor:'🧩'}},
 'measure':function(){var s=[['Đo bút chì bằng đơn vị nào?','cm',['cm','kg','lít','giờ']],['Đo nước trong chai bằng?','lít',['m','lít','kg','cm']],['Đo khối lượng bao gạo bằng?','kg',['kg','cm','lít','phút']]],x=s[Math.floor(Math.random()*s.length)];return {title:'Săn kho báu đo lường',q:x[0],answer:x[1],choices:v4Shuffle(x[2]),decor:'🗺️'}},
 'letters':function(){var s=[['Từ nào viết đúng?','nghỉ hè',['nghỉ hè','ngỉ hè','nghĩ hè','nghỉ hề']],['Điền âm đúng: “...ế đá”','gh',['g','gh','ng','ngh']]],x=s[Math.floor(Math.random()*s.length)];return {title:'Bắt chữ cái',q:x[0],answer:x[1],choices:v4Shuffle(x[2]),decor:'🐝'}},
 'spelling':function(){var s=[['Từ nào viết đúng?','sạch sẽ',['sạch sẽ','xạch sẽ','sạch sẻ','xạch sẻ']],['Từ nào viết đúng?','con nghé',['con ngé','con nghé','con ghé','con nghe']]],x=s[Math.floor(Math.random()*s.length)];return {title:'Thám tử chính tả',q:x[0],answer:x[1],choices:v4Shuffle(x[2]),decor:'🔎'}},
 'words':function(){return {title:'Ghép từ thần tốc',q:'Chọn câu đúng.',answer:'Em đang đọc sách.',choices:v4Shuffle(['Em đang đọc sách.','Đang em sách đọc.','Sách em đang đọc?','Đọc đang em sách.']),decor:'🧩'}},
 'story':function(){return {title:'Kể chuyện tranh',q:'Ai về đích trước trong truyện Thỏ và Rùa?',answer:'Rùa',choices:v4Shuffle(['Thỏ','Rùa','Cả hai','Không ai']),decor:'📚'}}
};
var V4GAME=null;
function game(type,variant){variant=variant||(type==='math'?'math-balloon':'letters');V4GAME={type:type,variant:variant,round:0,score:0,correct:0,answered:false};v4GameRound()}
function v4GameRound(){var s=V4GAME;if(s.round>=5)return v4FinishGame();var d=(V4GEN[s.variant]||V4GEN[s.type==='math'?'math-balloon':'letters'])();s.data=d;$('#app').innerHTML='<main class="game-page page-enter">'+top('Game mini - '+d.title,'green')+'<section class="playground"><div class="play-scene"><div class="game-round-badge">Vòng '+(s.round+1)+'/5</div><div class="floating-items"><span class="float-item f1">'+d.decor+'</span><span class="float-item f2">⭐</span><span class="float-item f3">'+d.decor+'</span><span class="float-item f4">🎯</span><span class="float-item f5">'+d.decor+'</span></div><div class="wood-question">'+v4Esc(d.q)+'</div><div class="player-kid">🧒🏻⚾</div><div class="game-answers">'+d.choices.map(function(a){return '<button data-v4ga="'+v4Esc(a)+'">'+v4Esc(a)+'</button>'}).join('')+'</div></div><aside class="game-info"><div class="game-mascot">🐯</div><h2>'+d.title+'</h2><p>Game dùng kiến thức đúng cấp lớp và kỹ năng bé đã học.</p><div class="score-card"><span>Điểm</span><b>'+s.score+' ⭐</b></div><div class="info-row"><span>Đúng</span><b>'+s.correct+'/'+s.round+'</b></div><div class="info-row"><span>Chuỗi học</span><b>'+state.streak+' ngày 🔥</b></div><button class="primary-btn" data-a="home">Về trang chủ</button></aside></section></main>';bind();$$('[data-v4ga]').forEach(function(b){b.onclick=function(){if(s.answered)return;s.answered=true;var ok=b.dataset.v4ga===d.answer;if(ok){b.classList.add('correct');s.correct++;s.score+=5;state.stars+=5;toast('🎯 Chính xác! +5 ⭐')}else{b.classList.add('wrong');var right=$$('[data-v4ga]').find(function(x){return x.dataset.v4ga===d.answer});if(right)right.classList.add('correct');toast('Gần đúng rồi!')}state.games++;save();setTimeout(function(){s.round++;s.answered=false;v4GameRound()},700)}})}
function v4FinishGame(){var s=V4GAME;$('#app').innerHTML='<main class="result-page page-enter green">'+top('Hoàn thành mini game','green')+'<section class="result-card"><div class="result-star">🏆</div><h1>Game hoàn thành!</h1><p>Con trả lời đúng <b>'+s.correct+'/5 vòng</b>, nhận <b>+'+s.score+' ⭐</b>.</p><div class="big-stars">'+'⭐'.repeat(Math.max(1,Math.ceil(s.correct/2)))+'</div><div class="result-actions"><button data-replay>Chơi lại</button><button class="primary-btn" data-a="home">Về trang chủ</button></div></section></main>';bind();$('[data-replay]').onclick=function(){game(s.type,s.variant)}}
